Repository JuliaCI/NanosoldierReports, pull requests merged in 2020-11, with the labels that each got.

#21 Fix CI, move to GH Actions
  .github/workflows/ci.yml
  .travis.yml
  tools/pkgeval_badges/src/cli.js
Labels: CI, badges, bug fix

#23 Add the workflow_dispatch trigger
  .github/workflows/ci.yml
Labels: CI

#22 Fix some whitespace
  README.md
Labels: documentation
